So I completely revamped the directories with building of models router connections instantiating routers and creating an app, some issues with global libraries and sql queries need a once over, I will post the queries I made in discord and in a wiki
G12-hc/tako-chart pull request #21
Opened 2024-12-04 15:48 UTC by Jake-Andrews-git

2024-12-04 16:16 UTC, crazybrain23 requested changes
Found a few oddities, also there's already a PR for the models #20, so this PR adding them would be redundant.

2024-12-04 16:16 UTC, crazybrain23 commented on .idea/dataSources.xml
> +      <jdbc-url>jdbc:postgresql://hc24_12:443/postgres</jdbc-url>
Wouldn't this only work on your system unless we host it locally exactly how you did?

2024-12-04 16:16 UTC, crazybrain23 commented on app/Stuff I don't need kinda/__init__.py
Why is does this exist?

2024-12-04 16:16 UTC, crazybrain23 commented on app/Stuff I don't need kinda/dataQueryTest.py
Same as above

2024-12-04 16:16 UTC, crazybrain23 commented on app/Stuff I don't need kinda/databaseConn.py
Same as above.

2024-12-04 16:16 UTC, crazybrain23 commented on app/Stuff I don't need kinda/prevmain.py
Is this temporary? At the very least add a comment saying it's just for testing.

2024-12-04 16:16 UTC, crazybrain23 commented on app/config.py
> +DATABASE_CONFIG = {
These will need to be in a secret file somewhere, to prevent secret leaking.

2024-12-04 16:16 UTC, crazybrain23 commented on app/db/connection.py
> +DB_CONFIG = {
Why is this duplicated (also in `__init__.py`)? Also it should get it from a secret file.

2024-12-04 17:22 UTC, crazybrain23 commented
What issues would this close?4

2024-12-04 18:09 UTC, not-Boris commented on app/main.py
> -    return  {"Hello": "World"}
:(

2024-12-05 11:32 UTC, celie2 approved these changes

2024-12-05 11:33 UTC, crazybrain23 approved these changes

2024-12-05 11:33 UTC, merged